language: d
sudo: false

matrix:
  include:
    - d: dmd-2.086.0
    - d: dmd-2.085.0
    - d: dmd-2.084.1
    - d: ldc-1.15.0
    - d: ldc-1.14.0
    - d: ldc-1.13.0

addons:
  apt:
    packages:
    - libclang-3.9-dev

script:
  - dub test --build=unittest-cov --compiler=${DC}

after_success:
 - bash <(curl -s https://codecov.io/bash)
