name: CI
on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Dub Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        dc:
          - dmd-2.096.1
          - dmd-2.095.0
          - ldc-1.26.0
          - ldc-1.20.0
        arch:
          - x86_64
        clang:
          - 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Setup Visual Studio Command Prompt - Windows
        if: startsWith(matrix.os,'windows')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup LLVM
        uses: KyleMayes/install-llvm-action@v1.4.0
        with:
          version: ${{ matrix.clang }}

      - name: Linux - link libclang.so
        if: contains(matrix.os, 'ubuntu')
        run: sudo ln -s libclang-${{ matrix.clang }}.so.1 /lib/x86_64-linux-gnu/libclang.so
        working-directory: ${{ env.LLVM_PATH }}/lib

      - name: Run tests
        run: dub test -q --build=unittest-cov --arch=${{ matrix.arch }}
        env:
          LIBRARY_PATH: "${{ env.LLVM_PATH }}/lib"

      - uses: codecov/codecov-action@v1
